name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  GH_PUB_KEY:
    github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
  GH_BOT_ACC_EMAIL:
    41898282+github-actions[bot]@users.noreply.github.com
  GH_BOT_ACC_NAME:
    github-actions[bot]

jobs:
  verify_coding_style_checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
          known_hosts: $GH_PUB_KEY
      - name: Setup Nix via cachix
        uses: cachix/install-nix-action@v20
      - name: Setup cachix cli
        run: nix-env -iA cachix -f https://cachix.org/api/v1/install
      - name: Install coding-style
        run: cachix use coding-style
      - name: Run
        run: |
          nix run github:Sigmapitech/cs --extra-experimental-features 'nix-command flakes'

  check_compilation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
          known_hosts: $GH_PUB_KEY
      - name: Setup Nix via cachix
        uses: cachix/install-nix-action@v20
      - name: Setup cachix cli
        run: nix-env -iA cachix -f https://cachix.org/api/v1/install
      - name: Install coding-style
        run: cachix use coding-style
      - name: Run
        run: |
          nix build

  fix_headers:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-names
        uses: tj-actions/branch-names@v6
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch-names.outputs.head_ref_branch }}
      - name: setup git
        run: |
          git config --local user.email $GH_BOT_ACC_EMAIL
          git config --local user.name $GH_BOT_ACC_NAME
          git fetch --unshallow origin
      - uses: actions/setup-python@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          python-version: '3.11'
          architecture: 'x64'
      - name: fix headers
        run: python ./.github/fix_headers.py
      - name: add to git
        run: |
          git add .
          git commit -m "[skip ci] Update epitech headers (auto)" || echo "nothing to commit."
      - name: push
        run: git push || echo "nothing to commit."

  sync_repository:
    needs: [ fix_headers, check_compilation, verify_coding_style_checker ]
    if: ${{ !github.event.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
          known_hosts: $GH_PUB_KEY
      - name: Unshallow
        run: |
          git config --global user.email "115845162+imjohntitor@users.noreply.github.com"
          git config --global user.name "ImJohnTitor"
          git remote add epitech "${{ secrets.GH_TARGET_REPO }}"
          git fetch --unshallow origin
      - name: Reset Author
        run : ./.github/workflows/reset_authors.sh
      - name: push to epitech
        run: |
          git push epitech main --force
